apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: dev-1
  labels:
     app: web-server-app
     version: v1
spec:
   replicas: 1
   selector: 
      matchLabels:
         app: web-server-app
         version: v1
   templete:
     metadata:
        servertimestamp: null
        labels:
           app: web-server-app
           version: v1
     spec:
      containers:
      - name: web-pp
        image: nginx
        ports:
        - containerPort: 80
          Protocol: TC
